#!/bin/bash
# Complete Nginx + Let's Encrypt TLS setup for an Agents44 Docker app on Lightsail.
#
# Usage:
#   sudo ./lightsail-tls.sh [dns_name] [backend_port] [email]
#
# Defaults:
#   dns_name     = agents.catch44.co.il
#   backend_port = 8080
#   email        = admin@catch44.co.il
#
# Examples:
#   sudo ./lightsail-tls.sh
#   sudo ./lightsail-tls.sh agents.catch44.co.il 8080
#   sudo ./lightsail-tls.sh tase44.catch44.co.il 8081 admin@catch44.co.il
#
# Prerequisites (do these before running):
#   1. DNS A record for <dns_name> → this VM's public IPv4
#   2. Lightsail firewall allows TCP 80 and 443
#   3. App container already listening: docker -p <backend_port>:80 ...
#
# Override DNS mismatch abort: FORCE_DNS=1 sudo ./lightsail-tls.sh ...
set -euo pipefail

DNS_NAME="${1:-agents.catch44.co.il}"
BACKEND_PORT="${2:-8080}"
CERTBOT_EMAIL="${3:-admin@catch44.co.il}"
FORCE_DNS="${FORCE_DNS:-0}"

if ! [[ "$BACKEND_PORT" =~ ^[0-9]+$ ]] || [ "$BACKEND_PORT" -lt 1 ] || [ "$BACKEND_PORT" -gt 65535 ]; then
  echo "Invalid backend port: $BACKEND_PORT" >&2
  exit 1
fi

if [ "$(id -u)" -ne 0 ]; then
  echo "Run with sudo: sudo $0 $*" >&2
  exit 1
fi

NGINX_AVAILABLE="/etc/nginx/sites-available/${DNS_NAME}"
NGINX_ENABLED="/etc/nginx/sites-enabled/${DNS_NAME}"
WEBROOT="/var/www/certbot"
LE_DIR="/etc/letsencrypt"
SSL_CERT="${LE_DIR}/live/${DNS_NAME}/fullchain.pem"
SSL_KEY="${LE_DIR}/live/${DNS_NAME}/privkey.pem"
SSL_OPTIONS="${LE_DIR}/options-ssl-nginx.conf"
SSL_DHPARAM="${LE_DIR}/ssl-dhparams.pem"

export DEBIAN_FRONTEND=noninteractive

echo "==> [1/7] Install nginx + certbot"
apt-get update -qq
apt-get install -y -qq nginx certbot openssl curl ca-certificates >/dev/null
mkdir -p "$WEBROOT" "$LE_DIR"
rm -f /etc/nginx/sites-enabled/default

echo "==> [2/7] Verify backend on 127.0.0.1:${BACKEND_PORT}"
if ! curl -fsS --max-time 3 "http://127.0.0.1:${BACKEND_PORT}/api/health" >/dev/null; then
  echo "ERROR: nothing healthy at http://127.0.0.1:${BACKEND_PORT}/api/health" >&2
  echo "       Start the app first, e.g.: ./lightsail-run.sh myname 'API_KEY' ${BACKEND_PORT}" >&2
  exit 1
fi
echo "  Backend OK"

echo "==> [3/7] Verify DNS points at this host"
PUBLIC_IP="$(curl -sS --max-time 5 http://checkip.amazonaws.com | tr -d '[:space:]' || true)"
RESOLVED="$(dig +short "$DNS_NAME" A 2>/dev/null | awk 'NF && $1 ~ /^[0-9.]+$/ {print; exit}')"
if [ -z "$RESOLVED" ]; then
  RESOLVED="$(getent ahostsv4 "$DNS_NAME" 2>/dev/null | awk '{print $1; exit}' || true)"
fi
echo "  Public IP: ${PUBLIC_IP:-unknown}"
echo "  DNS A:     ${RESOLVED:-unresolved}"
if [ -z "$PUBLIC_IP" ] || [ -z "$RESOLVED" ] || [ "$PUBLIC_IP" != "$RESOLVED" ]; then
  echo "ERROR: $DNS_NAME must resolve to this host (${PUBLIC_IP:-unknown}), got (${RESOLVED:-unresolved})" >&2
  echo "       Update the DNS A record, wait for propagation, then re-run." >&2
  if [ "$FORCE_DNS" != "1" ]; then
    exit 1
  fi
  echo "WARNING: FORCE_DNS=1 set — continuing anyway" >&2
fi

echo "==> [4/7] Write local TLS helper files (no network downloads)"
cat > "$SSL_OPTIONS" <<'SSLEOF'
# Generated by lightsail-tls.sh — used by nginx site configs.
ssl_session_cache shared:le_nginx_SSL:10m;
ssl_session_timeout 1440m;
ssl_session_tickets off;
ssl_protocols TLSv1.2 TLSv1.3;
ssl_prefer_server_ciphers off;
ssl_ciphers HIGH:!aNULL:!MD5;
SSLEOF

if [ ! -f "$SSL_DHPARAM" ]; then
  echo "  Generating DH params (one-time, ~30s)..."
  openssl dhparam -out "$SSL_DHPARAM" 2048
fi

write_http_bootstrap() {
  cat > "$NGINX_AVAILABLE" <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name ${DNS_NAME};

    location /.well-known/acme-challenge/ {
        root ${WEBROOT};
    }

    location / {
        proxy_pass http://127.0.0.1:${BACKEND_PORT};
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_read_timeout 300s;
    }
}
EOF
}

write_https_site() {
  cat > "$NGINX_AVAILABLE" <<EOF
server {
    listen 80;
    listen [::]:80;
    server_name ${DNS_NAME};

    location /.well-known/acme-challenge/ {
        root ${WEBROOT};
    }

    location / {
        return 301 https://\$host\$request_uri;
    }
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name ${DNS_NAME};

    ssl_certificate ${SSL_CERT};
    ssl_certificate_key ${SSL_KEY};
    include ${SSL_OPTIONS};
    ssl_dhparam ${SSL_DHPARAM};

    client_max_body_size 50m;

    location / {
        proxy_pass http://127.0.0.1:${BACKEND_PORT};
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_read_timeout 300s;
        proxy_buffering off;
    }
}
EOF
}

echo "==> [5/7] HTTP bootstrap for ACME + install nginx site"
write_http_bootstrap
ln -sfn "$NGINX_AVAILABLE" "$NGINX_ENABLED"
nginx -t
systemctl enable --now nginx
systemctl reload nginx

echo "==> [6/7] Obtain / renew Let's Encrypt certificate"
if [ -f "$SSL_CERT" ]; then
  echo "  Existing cert found — attempting renew"
  certbot renew --cert-name "$DNS_NAME" --non-interactive --deploy-hook "systemctl reload nginx" || true
else
  certbot certonly --webroot -w "$WEBROOT" \
    -d "$DNS_NAME" \
    --non-interactive --agree-tos --no-eff-email \
    -m "$CERTBOT_EMAIL"
fi

if [ ! -f "$SSL_CERT" ] || [ ! -f "$SSL_KEY" ]; then
  echo "ERROR: certificate files missing under ${LE_DIR}/live/${DNS_NAME}/" >&2
  exit 1
fi

echo "==> [7/7] Enable HTTPS termination → 127.0.0.1:${BACKEND_PORT}"
write_https_site
nginx -t
systemctl reload nginx
systemctl enable --now certbot.timer 2>/dev/null || true

echo ""
echo "==> Local verification"
curl -fsS --max-time 5 -H "Host: ${DNS_NAME}" "http://127.0.0.1/api/health" | head -c 200 || true
echo
curl -fsSk --max-time 5 "https://127.0.0.1/api/health" -H "Host: ${DNS_NAME}" | head -c 200 || true
echo

echo ""
echo "Done. TLS is configured end-to-end."
echo "  https://${DNS_NAME}/"
echo "  https://${DNS_NAME}/api/health"
echo "  Upstream: http://127.0.0.1:${BACKEND_PORT}"
echo ""
echo "Set the app public URL when (re)starting the container:"
echo "  FRONTEND_URL=https://${DNS_NAME} ./lightsail-run.sh <name> '<anthropic_key>' ${BACKEND_PORT}"
